### ISSUE TITLE
List of extensions to install

### ISSUE THREAD

**Issue by yochananmarqos** [emrecanaltinsoy/gnome-extensions-loader#2]
I created a new layout called "test" and hit apply. Where is it getting this list of extensions from? I do not have any of them installed currently, but I have in the past:

![Screenshot from 2021-09-25 13-59-38](https://user-images.githubusercontent.com/5437803/134784642-6c326862-bf49-4d37-b613-943e85391901.png)

If it makes a difference, all extensions are installed in `/usr/share/gnome-shell/extensions/` and there are none installed in `~/.local/share/gnome-shell/extensions/`

**Comment by emrecanaltinsoy** [comment]
this issue occurs when the extensions are removed without disabling them. these extensions stay enabled in /org/gnome/shell, even if they are not on the system.

**Comment by yochananmarqos** [comment]
Good grief. I'll have to see if I can find a related bug report, that's ridiculous. Do you know of any way to repopulate that key to get the current state?

**Comment by emrecanaltinsoy** [comment]
I changed it to overwrite the enabled-extensions key in the config file. Now it should work properly.

**Comment by yochananmarqos** [comment]
Now applying does nothing. There's no stdout or stderr, so it's a bit difficult to debug.

**Comment by emrecanaltinsoy** [comment]
It is probably because there is no change in the enabled/disabled extensions. I added a new messagebox to notify the changes are made.

**Comment by yochananmarqos** [comment]
The message box popped up generated a [config](https://pastebin.com/ffchvKMY), but there's still things in there from the old values.

```
❯ gnome-extensions list --enabled
background-logo@fedorahosted.org
appindicatorsupport@rgcjonas.gmail.com
auto-move-windows@gnome-shell-extensions.gcampax.github.com
gamemode@christian.kellner.me
pop-shell@system76.com
user-theme@gnome-shell-extensions.gcampax.github.com
gnome-ui-tune@itstime.tech
GPaste@gnome-shell-extensions.gnome.org
screenshotlocations.timur@linux.com
bluetooth-battery@michalw.github.com
disconnect-wifi@kgshank.net
bluetooth-quick-connect@bjarosze.gmail.com
x11gestures@joseexposito.github.io
sound-output-device-chooser@kgshank.net
expandable-notifications@kaan.g.inam.org
gsconnect@andyholmes.github.io
tweaks-system-menu@extensions.gnome-shell.fifi.org
lockkeys@vaina.lt
weatherintheclock@JasonLG1979.github.io
workspaces-bar@fthx
gnome-fuzzy-app-search@gnome-shell-extensions.Czarlie.gitlab.com
pamac-updates@manjaro.org
mullvadindicator@pobega.github.com
blur-my-shell@aunetx
```

```
❯ gnome-extensions list --disabled
apps-menu@gnome-shell-extensions.gcampax.github.com
arcmenu@arcmenu.com
dash-to-panel@jderose9.github.com
ding@rastersoft.com
drive-menu@gnome-shell-extensions.gcampax.github.com
launch-new-instance@gnome-shell-extensions.gcampax.github.com
material-shell@papyelgringo
native-window-placement@gnome-shell-extensions.gcampax.github.com
nightthemeswitcher@romainvigier.fr
places-menu@gnome-shell-extensions.gcampax.github.com
screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com
unite@hardpixel.eu
window-list@gnome-shell-extensions.gcampax.github.com
windowsNavigator@gnome-shell-extensions.gcampax.github.com
workspace-indicator@gnome-shell-extensions.gcampax.github.com
flypie@schneegans.github.com
vertical-overview@RensAlthuis.github.com
```

`/org/gnome/shell/enabled-extensions`:
```
['background-logo@fedorahosted.org', 'appindicatorsupport@rgcjonas.gmail.com', 'auto-move-windows@gnome-shell-extensions.gcampax.github.com', 'gamemode@christian.kellner.me', 'pop-shell@system76.com', 'user-theme@gnome-shell-extensions.gcampax.github.com', 'gnome-ui-tune@itstime.tech', 'GPaste@gnome-shell-extensions.gnome.org', 'screenshotlocations.timur@linux.com', 'bluetooth-battery@michalw.github.com', 'disconnect-wifi@kgshank.net', 'bluetooth-quick-connect@bjarosze.gmail.com', 'x11gestures@joseexposito.github.io', 'sound-output-device-chooser@kgshank.net', 'expandable-notifications@kaan.g.inam.org', 'gsconnect@andyholmes.github.io', 'tweaks-system-menu@extensions.gnome-shell.fifi.org', 'lockkeys@vaina.lt', 'weatherintheclock@JasonLG1979.github.io', 'workspaces-bar@fthx', 'gnome-fuzzy-app-search@gnome-shell-extensions.Czarlie.gitlab.com', 'pamac-updates@manjaro.org', 'mullvadindicator@pobega.github.com', 'blur-my-shell@aunetx', '']
```

`/org/gnome/shell/disabled-extensions`:
```
['material-shell@papyelgringo', 'unite@hardpixel.eu', 'status-area-horizontal-spacing@mathematical.coffee.gmail.com', 'freon@UshakovVasilii_Github.yahoo.com', 'floating-dock@nandoferreira_prof@hotmail.com', 'argos@pew.worldwidemann.com', 'horizontal-workspaces@gnome-shell-extensions.gcampax.github.com', 'wandering-pixel@justinrdonnelly.github.com', 'cast-to-tv-links-addon@rafostar.github.com', 'cast-to-tv-desktop-addon@rafostar.github.com', 'extensions-in-system-menu@leleat-on-github', 'arcmenu@arcmenu.com', 'blur-me@nunchucks', 'dash-to-panel@jderose9.github.com', 'shell-configurator@adeswanta', 'openweather-extension@jenslody.de', 'tiling-assistant@leleat-on-github', 'audio-switcher@albertomosconi', 'perfectionInShell@improvements', 'replaceActivitiesText@pratap.fastmail.fm', 'mprisindicatorbutton@JasonLG1979.github.io', 'dash-to-dock@micxgx.gmail.com', 'native-window-placement@gnome-shell-extensions.gcampax.github.com', 'nightthemeswitcher@romainvigier.fr', 'ding@rastersoft.com', 'flypie@schneegans.github.com', 'vertical-overview@RensAlthuis.github.com', 'workspace-indicator@gnome-shell-extensions.gcampax.github.com']
```

**Comment by emrecanaltinsoy** [comment]
It only overwrites the enabled-extensions key, since the app only reads that key from the config file to make changes.

**Comment by yochananmarqos** [comment]
Maybe reset the key and regenerate it before writing the config?

**Comment by emrecanaltinsoy** [comment]
it is now overwriting both keys.

**Comment by yochananmarqos** [comment]
I deleted the config folder before updating and it crashed creating a new layout:

```
Traceback (most recent call last):
  File "/usr/bin/gnome-extensions-loader", line 121, in add_layout
    self.write_conf(text)
  File "/usr/bin/gnome-extensions-loader", line 162, in write_conf
    self.config.set("extensions", "enabled-extensions", enabled)
  File "/usr/lib/python3.9/configparser.py", line 1204, in set
    super().set(section, option, value)
  File "/usr/lib/python3.9/configparser.py", line 902, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'extensions'
zsh: abort (core dumped)  gnome-extensions-loader
```

**Comment by emrecanaltinsoy** [comment]
Now it should work.

**Comment by yochananmarqos** [comment]
It does, but the generated config looks about the same. Still has values from extensions that are not installed.

**Comment by emrecanaltinsoy** [comment]
yes it's because the dconf keeps those values. I will remove those as well and only keep the ones that are on the system.

**Comment by emrecanaltinsoy** [comment]
I implemented this reading the path key in the extensions schema/xml file. It should be working now. If you see another problem, please create an issue. Thanks for your help.

**Comment by yochananmarqos** [comment]
`favorite-apps` has invalid desktop entries from removed applications.

I'm not sure what `command-history` has to do with anything.

`disabled-extensions` and `enabled-extensions` are correct now, though. Thanks! :+1: 

```
[/]
app-picker-layout = [{'system-tools': <{'position': <0>}>, 'accessories': <{'position': <1>}>, 'office': <{'position': <2>}>, 'webapp-manager.desktop': <{'position': <3>}>, 'firefox.desktop': <{'position': <4>}>, 'org.gnome.Geary.desktop': <{'position': <5>}>, 'simple-scan.desktop': <{'position': <6>}>, 'org.gnome.Totem.desktop': <{'position': <7>}>, 'org.gnome.Cheese.desktop': <{'position': <8>}>, 'org.gnome.Lollypop.desktop': <{'position': <9>}>, 'org.gnome.gThumb.desktop': <{'position': <10>}>, 'gnome-layouts.desktop': <{'position': <11>}>, 'manjaro-documentation.desktop': <{'position': <12>}>, 'org.gnome.Nautilus.desktop': <{'position': <13>}>, 'org.gnome.Maps.desktop': <{'position': <14>}>, 'org.manjaro.pamac.manager.desktop': <{'position': <15>}>}]
command-history = ['python /usr/lib/hidpi-daemon/hidpi-daemon', 'python /usr/lib/hidpi-daemon/hidpi-notification', '/usr/lib/hidpi-daemon/hidpi-daemon', '/usr/lib/hidpi-daemon/hidpi-notification', 'nc localhost 7634', 'clight', 'oryxkbleds --mode breathe', 'breathe.sh', 'sudo sys76-kb run -p pulse &', 'safeeyes', 'pulseffects --gapplication-service', 'opengothic.sh', 'monitor-off.sh', 'baru', 'conky-current.sh', 'r4', 'chromecast-mpris.sh', 'conan.sh', 'tilix-all.sh', 'pulseeffects --gapplication-service', 'easyeffects --gapplication-service', 'lg', 'badger --headless', 'com.github.elfenware.badger --headless', 'arch-audit-gtk', 'pop-launcher', 'exec electron13 /usr/lib/clipto/resources/app.asar "$@"', 'exec electron13 /usr/lib/clipto/resources/app.asar', 'cast-control.sh', 'clevo-indicator', 'r']
disable-user-extensions = false
disabled-extensions = ['apps-menu@gnome-shell-extensions.gcampax.github.com', 'arcmenu@arcmenu.com', 'dash-to-panel@jderose9.github.com', 'ding@rastersoft.com', 'drive-menu@gnome-shell-extensions.gcampax.github.com', 'launch-new-instance@gnome-shell-extensions.gcampax.github.com', 'material-shell@papyelgringo', 'native-window-placement@gnome-shell-extensions.gcampax.github.com', 'nightthemeswitcher@romainvigier.fr', 'places-menu@gnome-shell-extensions.gcampax.github.com', 'screenshot-window-sizer@gnome-shell-extensions.gcampax.github.com', 'unite@hardpixel.eu', 'window-list@gnome-shell-extensions.gcampax.github.com', 'windowsNavigator@gnome-shell-extensions.gcampax.github.com', 'workspace-indicator@gnome-shell-extensions.gcampax.github.com', 'flypie@schneegans.github.com', 'vertical-overview@RensAlthuis.github.com']
enabled-extensions = ['background-logo@fedorahosted.org', 'appindicatorsupport@rgcjonas.gmail.com', 'auto-move-windows@gnome-shell-extensions.gcampax.github.com', 'gamemode@christian.kellner.me', 'pop-shell@system76.com', 'user-theme@gnome-shell-extensions.gcampax.github.com', 'gnome-ui-tune@itstime.tech', 'GPaste@gnome-shell-extensions.gnome.org', 'screenshotlocations.timur@linux.com', 'bluetooth-battery@michalw.github.com', 'disconnect-wifi@kgshank.net', 'bluetooth-quick-connect@bjarosze.gmail.com', 'x11gestures@joseexposito.github.io', 'sound-output-device-chooser@kgshank.net', 'expandable-notifications@kaan.g.inam.org', 'gsconnect@andyholmes.github.io', 'tweaks-system-menu@extensions.gnome-shell.fifi.org', 'lockkeys@vaina.lt', 'weatherintheclock@JasonLG1979.github.io', 'workspaces-bar@fthx', 'gnome-fuzzy-app-search@gnome-shell-extensions.Czarlie.gitlab.com', 'pamac-updates@manjaro.org', 'mullvadindicator@pobega.github.com', 'blur-my-shell@aunetx']
favorite-apps = ['pop-cosmic-launcher.desktop', 'pop-cosmic-workspaces.desktop', 'pop-cosmic-applications.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.gedit.desktop', 'com.gexperts.Tilix.desktop', 'org.manjaro.pamac.manager.desktop', 'google-chrome.desktop', 'chrome-eilembjdkfgodjkcjnpgpaenohkicgjd-Default.desktop', 'joindesktop.desktop', 'clipto.desktop', 'telegramdesktop.desktop', 'android-messages-desktop.desktop', 'org.qbittorrent.qBittorrent.desktop', 'jdownloader.desktop', 'drill-search-gtk.desktop']
had-bluetooth-devices-setup = true
looking-glass-history = ['Main.overview._overview.controls._appDisplay._folderIcons[0]']
welcome-dialog-last-shown-version = '40.0'
```

**Comment by emrecanaltinsoy** [comment]
```
dconf dump /org/gnome/shell/
```
dumps all these values. I will probably remove all the keys except enabled-extensions and disabled-extensions. I may even remove the disabled-extensions key, because it is not used by the app to install or enable/disable extensions.

**Comment by emrecanaltinsoy** [comment]
Removed the unnecessary keys from the conf files. Also, some extensions such as custom-hot-corners were not saved, fixed that issue as well. The main problem is some extensions do not follow the same template as the rest. If I encounter another issue regarding this, I will check it more.

**Comment by yochananmarqos** [comment]
> The message box popped up generated a [config](https://pastebin.com/ffchvKMY)

Off topic, but would you believe Pastebin removed that paste due to "abuse reports"? Apparently it's an automated system. I had to email them to get it restored. I didn't even know which paste it was  they "quarantined" because they only provided the ID.
